### ISSUE TITLE
Provide unminified versions of CSS files

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/common-style#104]
Currently, `common-style` only generates minified CSS files. It should generate non-minified CSS files as well.

**Comment by ByronDarlison** [comment]
@donnapep is this still an issue? And if it is, I am assuming this is something that @ghislaineguerin or @RV-Adrian should correct. Can you confirm? Thanks

**Comment by donnapep** [comment]
@ByronDarlison Yes, it's still an issue. It's a change to the Gulpfile. Not sure if they're comfortable with that.

**Comment by RV-Adrian** [comment]
@ByronDarlison @ghislaineguerin @donnapep 
I think we can take this one on.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lcvYkTKK&#x2F;1114-provide-unminified-versions-of-css-files"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Provide unminified versions of CSS files</a>

**Comment by ByronDarlison** [comment]
@RV-Adrian @donnapep okay. Moving to card. Thanks

**Comment by RV-Adrian** [comment]
@donnapep 
Pending PR for this at https://github.com/Rise-Vision/common-style/pull/240

I've named it 'rise.css' in the same dist/ directory. Let me know if you'd like anything modified. Thx!

**Comment by RV-Adrian** [comment]
Update: Issue fixed and tested
